name: wasteapp
description: A new Flutter project.
publish_to: 'none' 

environment:
  # sdk: ">=2.16.2 <3.0.0"
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  

  cupertino_icons: ^1.0.8
  mpesa_flutter_plugin: ^1.6.1
  intl: ^0.17.0 
  firebase_core: ^3.15.2
  firebase_auth: any
  cloud_firestore: ^5.6.12  
  http: ^0.13.6
  fl_chart: ^1.1.1
  mpesa: ^2.0.2
  flutterwave_standard: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true


